// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMcpServer(arg1:string):Promise<string>;

export function BrowseFile():Promise<string>;

export function BrowseFolder():Promise<string>;

export function CheckAllSkillUpdates():Promise<string>;

export function CheckSkillUpdate(arg1:string):Promise<string>;

export function CreateSource(arg1:string):Promise<string>;

export function DeleteMcpServer(arg1:string):Promise<string>;

export function DeleteSkill(arg1:string):Promise<string>;

export function DeleteSource(arg1:string):Promise<string>;

export function DetectTools():Promise<string>;

export function DisableMcpForTool(arg1:string,arg2:string):Promise<string>;

export function DisableSkillForTool(arg1:string,arg2:string):Promise<string>;

export function DisableTool(arg1:string):Promise<string>;

export function DiscoverMcpTools(arg1:string):Promise<string>;

export function EnableMcpForTool(arg1:string,arg2:string):Promise<string>;

export function EnableSkillForTool(arg1:string,arg2:string):Promise<string>;

export function EnableTool(arg1:string):Promise<string>;

export function ExportSkillsZip(arg1:string):Promise<string>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetGitStatus(arg1:string):Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetMcpServer(arg1:string):Promise<string>;

export function GetSettings():Promise<string>;

export function GetSkill(arg1:string):Promise<string>;

export function GetSkillDetail(arg1:string):Promise<string>;

export function GetSkillVersionDiff(arg1:string):Promise<string>;

export function GitPull(arg1:string):Promise<string>;

export function ImportSkillsZip(arg1:string):Promise<string>;

export function InstallSkillFromGit(arg1:string):Promise<string>;

export function InstallSkillFromLocal(arg1:string):Promise<string>;

export function ListActivities(arg1:number):Promise<string>;

export function ListGitBranches(arg1:string,arg2:string):Promise<string>;

export function ListMcpServers(arg1:number,arg2:number,arg3:string):Promise<string>;

export function ListSkills(arg1:number,arg2:number,arg3:string,arg4:string):Promise<string>;

export function ListSources():Promise<string>;

export function ListTools():Promise<string>;

export function OpenInExplorer(arg1:string):Promise<string>;

export function ResetSettings():Promise<string>;

export function SaveFile(arg1:string):Promise<string>;

export function SearchMarketplace(arg1:string):Promise<string>;

export function SearchMcpMarketplace(arg1:string):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<string>;

export function SyncAllMcp():Promise<string>;

export function SyncAllSkills():Promise<string>;

export function SyncMcpToTool(arg1:string,arg2:string):Promise<string>;

export function SyncSkillToTool(arg1:string,arg2:string):Promise<string>;

export function UnsyncMcpFromTool(arg1:string,arg2:string):Promise<string>;

export function UnsyncSkillFromTool(arg1:string,arg2:string):Promise<string>;

export function UpdateMcpServer(arg1:string,arg2:string):Promise<string>;
