// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMcpServer(arg1) {
  return window['go']['main']['App']['AddMcpServer'](arg1);
}

export function BrowseFile() {
  return window['go']['main']['App']['BrowseFile']();
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function CreateSource(arg1) {
  return window['go']['main']['App']['CreateSource'](arg1);
}

export function DeleteMcpServer(arg1) {
  return window['go']['main']['App']['DeleteMcpServer'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteSource(arg1) {
  return window['go']['main']['App']['DeleteSource'](arg1);
}

export function DetectTools() {
  return window['go']['main']['App']['DetectTools']();
}

export function DisableMcpForTool(arg1, arg2) {
  return window['go']['main']['App']['DisableMcpForTool'](arg1, arg2);
}

export function DisableSkillForTool(arg1, arg2) {
  return window['go']['main']['App']['DisableSkillForTool'](arg1, arg2);
}

export function DisableTool(arg1) {
  return window['go']['main']['App']['DisableTool'](arg1);
}

export function DiscoverMcpTools(arg1) {
  return window['go']['main']['App']['DiscoverMcpTools'](arg1);
}

export function EnableMcpForTool(arg1, arg2) {
  return window['go']['main']['App']['EnableMcpForTool'](arg1, arg2);
}

export function EnableSkillForTool(arg1, arg2) {
  return window['go']['main']['App']['EnableSkillForTool'](arg1, arg2);
}

export function EnableTool(arg1) {
  return window['go']['main']['App']['EnableTool'](arg1);
}

export function ExportSkillsZip(arg1) {
  return window['go']['main']['App']['ExportSkillsZip'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetMcpServer(arg1) {
  return window['go']['main']['App']['GetMcpServer'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSkillDetail(arg1) {
  return window['go']['main']['App']['GetSkillDetail'](arg1);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function ImportSkillsZip(arg1) {
  return window['go']['main']['App']['ImportSkillsZip'](arg1);
}

export function InstallSkillFromGit(arg1) {
  return window['go']['main']['App']['InstallSkillFromGit'](arg1);
}

export function InstallSkillFromLocal(arg1) {
  return window['go']['main']['App']['InstallSkillFromLocal'](arg1);
}

export function ListActivities(arg1) {
  return window['go']['main']['App']['ListActivities'](arg1);
}

export function ListGitBranches(arg1, arg2) {
  return window['go']['main']['App']['ListGitBranches'](arg1, arg2);
}

export function ListMcpServers(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListMcpServers'](arg1, arg2, arg3);
}

export function ListSkills(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSkills'](arg1, arg2, arg3, arg4);
}

export function ListSources() {
  return window['go']['main']['App']['ListSources']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SearchMarketplace(arg1) {
  return window['go']['main']['App']['SearchMarketplace'](arg1);
}

export function SearchMcpMarketplace(arg1) {
  return window['go']['main']['App']['SearchMcpMarketplace'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SyncAllMcp() {
  return window['go']['main']['App']['SyncAllMcp']();
}

export function SyncAllSkills() {
  return window['go']['main']['App']['SyncAllSkills']();
}

export function SyncMcpToTool(arg1, arg2) {
  return window['go']['main']['App']['SyncMcpToTool'](arg1, arg2);
}

export function SyncSkillToTool(arg1, arg2) {
  return window['go']['main']['App']['SyncSkillToTool'](arg1, arg2);
}

export function UnsyncMcpFromTool(arg1, arg2) {
  return window['go']['main']['App']['UnsyncMcpFromTool'](arg1, arg2);
}

export function UnsyncSkillFromTool(arg1, arg2) {
  return window['go']['main']['App']['UnsyncSkillFromTool'](arg1, arg2);
}

export function UpdateMcpServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateMcpServer'](arg1, arg2);
}
